spring.application.name=video-platform

spring.config.import=optional:file:.env.properties

spring.datasource.url=${SUPABASE_DATABASE_URL}
spring.datasource.driver-class-name=org.postgresql.Driver

supabase.jwks.url=${SUPABASE_JWKS_URL}

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl